server:
  port: 9000

spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=auth
    username: "postgres"
    password: "postgres"
    driver-class-name: org.postgresql.Driver
  jackson:
    deserialization:
      FAIL_ON_IGNORED_PROPERTIES: false
    serialization:
      INDENT_OUTPUT: false
      WRITE_DATES_AS_TIMESTAMPS: false
      WRITE_BIGDECIMAL_AS_PLAIN: true
  sql:
    init:
      mode: always
